apiVersion: v1
kind: Service
metadata:
  name: utm-spring-boot-mc-mm-service
spec:
  selector:
    app: utm-spring-boot-mc-mm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer