apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-lab-1-deployment
spec:
  replicas: 3  # Specifies the number of instances you want running
  selector:
    matchLabels:
      app: ac-lab-1
  template:
    metadata:
      labels:
        app: ac-lab-1
    spec:
      containers:
      - name: ac-lab-1
        image: felixbirca2/ac-lab-1:latest
        ports:
        - containerPort: 8080  # Adjust the port if your app uses a different one
