kind: Service
apiVersion: v1
metadata:
  name: ac-lab-fin
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32000
  selector:
    app: ac-lab-fin
