name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build_jar:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.7.0-jdk17

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Assemble JAR
        run: ./gradlew bootJar
