name: Azure Login and Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deployment version to rollback to'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Connect to AKS
      run: |
        az aks get-credentials --resource-group <YourResourceGroup> --name <YourClusterName> --overwrite-existing

    - name: Rollback to previous deployment version
      run: kubectl rollout undo deployment/<your-deployment-name> --to-revision=${{ github.event.inputs.version }}
